import java.util.ArrayList;
import java.util.List;
public class Main {
  public static void main(String[] args){
     ResponsibleTeacher teacher1 = new ResponsibleTeacher("Mouse", "Mickey");
     teacher1.setBirthDate("230498-045T");
     MonthlyPayment monthlyPayment = new MonthlyPayment();
     monthlyPayment.setSalary(756.85);
     teacher1.setPayment(monthlyPayment);
     AssistantTeacher teacher2 = new AssistantTeacher("The Dog", "Goofy");
     teacher2.setBirthDate("141200A2315");
     HourBasedPayment hourBasedPayment = new HourBasedPayment();
     hourBasedPayment.setEurosPerHour(3.5);
     hourBasedPayment.setHours(11.0);
     teacher2.setPayment(hourBasedPayment);
     Student student = new Student("Duck", "Donald");
     Course course1 = new Course( "Programming 1", 811104, 'P', 1, 1, 5.0, true);
     Course course2 = new Course("All kinds of basic studies", 112233, 'P', 1, 2, 45.0,  true);
     Course course3 = new Course("More basic studies", 223344, 'a', 1, 1, 50.5, true);
     Course course4 = new Course("Even more basic studies", 556677, 'a', 0, 3, 50.0, true);
     Course course5 = new Course("Final basic studies", 123123, 'A', 1, 4, 50.5, true);
     Course course6 = new Course("Programming 2", 616161, 'A', 1, 3, 25.0, true);
     Course course7 = new Course("All kinds of master studies", 717171, 'P', 0, 2, 45.0, true);
     Course course8 = new Course("More master studies", 818181, 'A', 1, 1, 25.0, true);
     Course course9 = new Course("Even more master studies ", 919191, 'S', 1, 3, 20.0, true);
     Course course10 = new Course("Extra master studies", 666666, 'S', 0, 5, 8.0, false);
     Course course11 = new Course("Final master studies", 888888, 'S', 1, 5, 18.0, false);
     List<DesignatedCourse> courses = new ArrayList<DesignatedCourse>();
     DesignatedCourse dCourse3 = new DesignatedCourse(course3, true, 2023);
     DesignatedCourse dCourse4 = new DesignatedCourse(course4, true, 2023);
     DesignatedCourse dCourse10 = new DesignatedCourse(course10, true, 2022);
     DesignatedCourse dCourse11 = new DesignatedCourse(course11, true, 2023);
     courses.add(dCourse3);
     courses.add(dCourse4);
     courses.add(dCourse10);
     courses.add(dCourse11);
     teacher1.setCourses(courses);
     teacher2.setCourses(courses);
     System.out.println(teacher1.toString());
     System.out.println(teacher2.toString());
     StudentCourse studentCourse1 = new StudentCourse(course1, 1, 2013);
     StudentCourse studentCourse2 = new StudentCourse(course2, 1, 2014);
     StudentCourse studentCourse3 = new StudentCourse(course3, 1, 2015);
     StudentCourse studentCourse4 = new StudentCourse(course4, 4, 2016);
     StudentCourse studentCourse5 = new StudentCourse(course5, 5, 2017);
     StudentCourse studentCourse6 = new StudentCourse(course6, 1, 2018);
     StudentCourse studentCourse7 = new StudentCourse(course7, 1, 2019);
     StudentCourse studentCourse8 = new StudentCourse(course8, 2, 2020);
     StudentCourse studentCourse9 = new StudentCourse(course9, 0, 2021);
     StudentCourse studentCourse10 = new StudentCourse(course10, 'A', 2021);
     StudentCourse studentCourse11 = new StudentCourse(course11, 'f', 2022);
     ArrayList<StudentCourse> bachelor = new ArrayList<StudentCourse>();
     bachelor.add(studentCourse1);
     bachelor.add(studentCourse2);
     bachelor.add(studentCourse3);
     bachelor.add(studentCourse4);
     bachelor.add(studentCourse5);
     ArrayList<StudentCourse> master = new ArrayList<StudentCourse>();
     master.add(studentCourse6);
     master.add(studentCourse7);
     master.add(studentCourse8);
     master.add(studentCourse9);
     master.add(studentCourse10);
     master.add(studentCourse11);
     student.addCourses(0, bachelor);
     student.addCourses(1, master);
     student.setDegreeTitle(0, "Bachelor of Science");
     student.setDegreeTitle(1, "Master of Science");
     student.setTitleOfThesis(0, "Bachelor thesis title");
     student.setTitleOfThesis(1, "Masters thesis title");
     student.setStartYear(2001);
     student.setGraduationYear(2020);
     System.out.println(student.toString());
     student.setBirthDate("230498-045T");
     student.setTitleOfThesis(0, "Christmas - The most wonderful time of the year");
     student.setTitleOfThesis(1, "Dreaming of a white Christmas");
     studentCourse9.setGrade(3);
     System.out.println(student.toString());
     student.printDegrees();
     student.printCourses();
     System.out.println('\n');
     studentCourse11.setGrade('X');
     System.out.println(studentCourse11.toString());
     studentCourse11.setGrade('a');
     System.out.println(studentCourse11.toString());   
     studentCourse1.setGrade(6);
     System.out.println(studentCourse1.toString());
     studentCourse1.setGrade(5);
     System.out.println(studentCourse1.toString());
     
     
     Student student1 = new Student("Duck", "Daisy");

    ArrayList<StudentCourse> bachelorC =  new ArrayList<>();
    bachelorC.add(studentCourse1);
    bachelorC.add(studentCourse2);
    bachelorC.add(studentCourse3);
    ArrayList<StudentCourse> masterC = new ArrayList<>();
    masterC.add(studentCourse9);
    masterC.add(studentCourse10);
    masterC.add(studentCourse11);

    Degree bachelor1 = new Degree();
    Degree master1 = new Degree();
    student1.setDegreeTitle(0, "Bachelor of Science");
    student1.setTitleOfThesis(0, "ABC");
    student1.setDegreeTitle(1, "Master of Science");
    student1.setTitleOfThesis(1, "DEF");
    student1.addCourses(0, bachelorC);
    student1.addCourses(1, masterC);
    student1.setStartYear(2011);
    student1.setGraduationYear(2020);
    System.out.println(student1.toString());
    student1.printDegrees();
    student1.setBirthDate("120944-8638");
    studentCourse9.setGrade(3);
    student1.setGraduationYear(2022);
    System.out.println(student1.toString());
    student1.printDegrees();
   }
}
